from turtle import Turtle
ted = Turtle()
ted.speed(10)

# a great-looking perspective with terrible angles
# trust me when i say i got out a protractor for this

# ref. image: f4.bcbits.com/img/a1267169815_10.jpg 
# from: petalportmusic.bandcamp.com/album/hes-not-with-us-anymore
# biggest problem is that x11 colors are garbage

ted.pencolor('white')
ted.penup()
ted.sety(-50)
ted.pendown()
ted.fillcolor('rebecca purple')
ted.begin_fill()
ted.left(180)
ted.forward(200)
ted.right(90)
ted.forward(400)
ted.right(90)
ted.forward(400)
ted.right(90)
ted.forward(400)
ted.end_fill()
ted.penup()
ted.home()
ted.pendown()


ted.pencolor('black')
ted.fillcolor('cornsilk')
ted.begin_fill()
#room
ted.left(27)
ted.forward(200)
ted.left(63)
ted.forward(100)
ted.left(63)
ted.forward(200)

ted.left(117)
ted.forward(100)
ted.left(63)
ted.forward(200)

ted.penup()
ted.home()
ted.pendown()

ted.right(207)
ted.forward(200)

ted.right(63)
ted.forward(100)
ted.right(63)
ted.forward(200)
ted.right(117)
ted.forward(100)
ted.right(63)
ted.forward(200)
ted.end_fill()

  #floor color
ted.penup()
ted.home()
ted.pendown()
ted.fillcolor('dark olive green')
ted.begin_fill()
ted.left(27)
ted.forward(200)
ted.left(126)
ted.forward(200)
ted.left(54)
ted.forward(200)
ted.left(126)
ted.forward(200)
ted.end_fill()
ted.penup()
ted.right(180)
ted.forward(200)
ted.left(54)
ted.pendown()

#door
ted.fillcolor('sienna')
ted.begin_fill()
ted.right(180)
ted.forward(50)
ted.left(64)
ted.forward(70)
ted.right(63)
ted.forward(30)
ted.right(116.9)
ted.forward(70)
ted.end_fill()
  #door handle
ted.fillcolor('peru')
ted.begin_fill()
ted.right(180)
ted.forward(25)
ted.left(117)
ted.forward(10)
ted.right(117)
ted.forward(10)
ted.right(63)
ted.forward(10)
ted.end_fill()

ted.penup()
ted.home()

#bed (no time for sheets!)
ted.setx(60)
ted.sety(42)
ted.right(1)

ted.fillcolor('lavender')
ted.begin_fill()
ted.pendown()
ted.left(27)
ted.forward(90)
ted.left(63)
ted.forward(20)
ted.left(63)
ted.forward(100)
ted.left(55)
ted.forward(90)
ted.left(63)
ted.forward(20)
ted.left(63)
ted.forward(100)
ted.right(243)
ted.forward(20)
ted.left(63)
ted.forward(100)
ted.right(180)
ted.forward(100)
ted.left(53)
ted.forward(90)
ted.right(180)
ted.forward(90)
ted.left(63)
ted.forward(20)
ted.end_fill()

#windows (curtains)
ted.penup()
ted.setx(20)
ted.sety(180)
ted.pendown()
ted.fillcolor('coral')

ted.begin_fill()
ted.right(178)
ted.forward(75)
ted.right(117)
ted.forward(70)
ted.right(63)
ted.forward(75)
ted.end_fill() # these shapes don't have that final outline to act as if they don't /end/ here (perhaps folded back or frayed)

ted.penup()
ted.setx(100)
ted.sety(141)
ted.pendown()

ted.begin_fill()
ted.right(181)
ted.forward(75)
ted.right(117)
ted.forward(70)
ted.right(63)
ted.forward(75)
ted.end_fill()

#pillows (stringed on to the end as to not mess up the curtains)
ted.penup()
ted.setx(105)
ted.sety(115)
ted.pendown()

ted.fillcolor('Papaya Whip')
ted.begin_fill()
ted.right(70)
ted.forward(30)
ted.circle(3, 90)
ted.forward(12)
ted.circle(3, 90)
ted.forward(30)
ted.circle(3, 90)
ted.forward(12)
ted.circle(3, 90)
ted.end_fill()

# ran out of time for the tv and curtain shadows
# "finished is better than perfect"